/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author myusuf, fairuz, diniyal
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form Adminpage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelAddCar = new javax.swing.JPanel();
        txPoliceNum = new javax.swing.JTextField();
        jButtonAddCar = new javax.swing.JButton();
        txCapacity = new javax.swing.JTextField();
        txBrand = new javax.swing.JTextField();
        jLabelAddCar = new javax.swing.JLabel();
        jPanelAddDriver = new javax.swing.JPanel();
        txDriverName = new javax.swing.JTextField();
        txIdNumber = new javax.swing.JTextField();
        jButtonAddDriver = new javax.swing.JButton();
        jComboBoxCar = new javax.swing.JComboBox<>();
        jLabelAddDriver = new javax.swing.JLabel();
        jPaneHeader = new javax.swing.JPanel();
        jButtonSignOut = new javax.swing.JButton();
        jPanelAdminName = new javax.swing.JPanel();
        jLabelAdminName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTransaction = new javax.swing.JLabel();
        txCustomerName = new javax.swing.JTextField();
        txDestination = new javax.swing.JTextField();
        txDate = new javax.swing.JTextField();
        txPrice = new javax.swing.JTextField();
        jComboBoxDriver = new javax.swing.JComboBox<>();
        jButtonAddTransaction = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonShowCars = new javax.swing.JButton();
        jButtonShowDrivers = new javax.swing.JButton();
        jButtonShowCustomers = new javax.swing.JButton();
        jButtonShowTransactions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel");
        setBackground(new java.awt.Color(252, 252, 252));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(558, 500));
        setName("AdminPage"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(558, 500));

        jTabbedPaneMenu.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneMenu.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jTabbedPaneMenu.setOpaque(true);

        jPanelAddCar.setBackground(new java.awt.Color(255, 255, 255));

        txPoliceNum.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txPoliceNum.setForeground(new java.awt.Color(204, 204, 204));
        txPoliceNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPoliceNum.setText("Police Number");
        txPoliceNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txPoliceNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txPoliceNum.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txPoliceNum.setPreferredSize(new java.awt.Dimension(122, 35));
        txPoliceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPoliceNumActionPerformed(evt);
            }
        });

        jButtonAddCar.setBackground(new java.awt.Color(62, 158, 202));
        jButtonAddCar.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonAddCar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddCar.setText("Add");
        jButtonAddCar.setBorder(null);
        jButtonAddCar.setContentAreaFilled(false);
        jButtonAddCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddCar.setOpaque(true);
        jButtonAddCar.setPreferredSize(new java.awt.Dimension(100, 35));

        txCapacity.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txCapacity.setForeground(new java.awt.Color(204, 204, 204));
        txCapacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txCapacity.setText("Capacity");
        txCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txCapacity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txCapacity.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txCapacity.setPreferredSize(new java.awt.Dimension(122, 35));
        txCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCapacityActionPerformed(evt);
            }
        });

        txBrand.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txBrand.setForeground(new java.awt.Color(204, 204, 204));
        txBrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txBrand.setText("Brand");
        txBrand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txBrand.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txBrand.setPreferredSize(new java.awt.Dimension(122, 35));
        txBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBrandActionPerformed(evt);
            }
        });

        jLabelAddCar.setFont(new java.awt.Font("Typo Style Demo", 0, 14)); // NOI18N
        jLabelAddCar.setForeground(new java.awt.Color(153, 0, 0));
        jLabelAddCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelAddCarLayout = new javax.swing.GroupLayout(jPanelAddCar);
        jPanelAddCar.setLayout(jPanelAddCarLayout);
        jPanelAddCarLayout.setHorizontalGroup(
            jPanelAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txPoliceNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(txBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jButtonAddCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddCarLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabelAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );
        jPanelAddCarLayout.setVerticalGroup(
            jPanelAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddCarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txPoliceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButtonAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanelAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddCarLayout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(jLabelAddCar)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        jTabbedPaneMenu.addTab("Add Car", jPanelAddCar);

        jPanelAddDriver.setBackground(new java.awt.Color(255, 255, 255));

        txDriverName.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txDriverName.setForeground(new java.awt.Color(204, 204, 204));
        txDriverName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txDriverName.setText("Name");
        txDriverName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txDriverName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txDriverName.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txDriverName.setPreferredSize(new java.awt.Dimension(122, 35));
        txDriverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDriverNameActionPerformed(evt);
            }
        });

        txIdNumber.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txIdNumber.setForeground(new java.awt.Color(204, 204, 204));
        txIdNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txIdNumber.setText("Id Number");
        txIdNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txIdNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txIdNumber.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txIdNumber.setPreferredSize(new java.awt.Dimension(122, 35));
        txIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdNumberActionPerformed(evt);
            }
        });

        jButtonAddDriver.setBackground(new java.awt.Color(62, 158, 202));
        jButtonAddDriver.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonAddDriver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddDriver.setText("Add");
        jButtonAddDriver.setBorder(null);
        jButtonAddDriver.setContentAreaFilled(false);
        jButtonAddDriver.setOpaque(true);
        jButtonAddDriver.setPreferredSize(new java.awt.Dimension(100, 35));

        jComboBoxCar.setBackground(new java.awt.Color(62, 158, 202));
        jComboBoxCar.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jComboBoxCar.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxCar.setMaximumRowCount(5);
        jComboBoxCar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 245, 245)));
        jComboBoxCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxCar.setPreferredSize(new java.awt.Dimension(90, 35));
        jComboBoxCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCarActionPerformed(evt);
            }
        });

        jLabelAddDriver.setFont(new java.awt.Font("Typo Style Demo", 0, 14)); // NOI18N
        jLabelAddDriver.setForeground(new java.awt.Color(153, 0, 0));
        jLabelAddDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelAddDriverLayout = new javax.swing.GroupLayout(jPanelAddDriver);
        jPanelAddDriver.setLayout(jPanelAddDriverLayout);
        jPanelAddDriverLayout.setHorizontalGroup(
            jPanelAddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDriverName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txIdNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jButtonAddDriver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelAddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddDriverLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabelAddDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );
        jPanelAddDriverLayout.setVerticalGroup(
            jPanelAddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDriverLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButtonAddDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanelAddDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddDriverLayout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jLabelAddDriver)
                    .addContainerGap(108, Short.MAX_VALUE)))
        );

        jTabbedPaneMenu.addTab("Add Driver", jPanelAddDriver);

        jPaneHeader.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSignOut.setBackground(new java.awt.Color(62, 158, 202));
        jButtonSignOut.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonSignOut.setForeground(new java.awt.Color(62, 158, 202));
        jButtonSignOut.setText("SignOut");
        jButtonSignOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 211, 213)));
        jButtonSignOut.setContentAreaFilled(false);
        jButtonSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSignOut.setMultiClickThreshhold(5L);
        jButtonSignOut.setPreferredSize(new java.awt.Dimension(100, 35));

        jPanelAdminName.setBackground(new java.awt.Color(62, 158, 202));

        jLabelAdminName.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelAdminName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAdminName.setPreferredSize(new java.awt.Dimension(200, 35));

        javax.swing.GroupLayout jPanelAdminNameLayout = new javax.swing.GroupLayout(jPanelAdminName);
        jPanelAdminName.setLayout(jPanelAdminNameLayout);
        jPanelAdminNameLayout.setHorizontalGroup(
            jPanelAdminNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAdminName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAdminNameLayout.setVerticalGroup(
            jPanelAdminNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAdminName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPaneHeaderLayout = new javax.swing.GroupLayout(jPaneHeader);
        jPaneHeader.setLayout(jPaneHeaderLayout);
        jPaneHeaderLayout.setHorizontalGroup(
            jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdminName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneHeaderLayout.setVerticalGroup(
            jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTransaction.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelTransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTransaction.setText("Transaction");

        txCustomerName.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txCustomerName.setForeground(new java.awt.Color(204, 204, 204));
        txCustomerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txCustomerName.setText("Name");
        txCustomerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txCustomerName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txCustomerName.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txCustomerName.setPreferredSize(new java.awt.Dimension(122, 35));
        txCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCustomerNameActionPerformed(evt);
            }
        });

        txDestination.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txDestination.setForeground(new java.awt.Color(204, 204, 204));
        txDestination.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txDestination.setText("Destination");
        txDestination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txDestination.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txDestination.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txDestination.setPreferredSize(new java.awt.Dimension(122, 35));
        txDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDestinationActionPerformed(evt);
            }
        });

        txDate.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txDate.setForeground(new java.awt.Color(204, 204, 204));
        txDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txDate.setText("Date");
        txDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txDate.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txDate.setPreferredSize(new java.awt.Dimension(122, 35));
        txDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDateActionPerformed(evt);
            }
        });

        txPrice.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txPrice.setForeground(new java.awt.Color(204, 204, 204));
        txPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPrice.setText("Price");
        txPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txPrice.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txPrice.setPreferredSize(new java.awt.Dimension(122, 35));
        txPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPriceActionPerformed(evt);
            }
        });

        jComboBoxDriver.setBackground(new java.awt.Color(62, 158, 202));
        jComboBoxDriver.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jComboBoxDriver.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxDriver.setMaximumRowCount(5);
        jComboBoxDriver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 245, 245)));
        jComboBoxDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxDriver.setPreferredSize(new java.awt.Dimension(90, 35));
        jComboBoxDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDriverActionPerformed(evt);
            }
        });

        jButtonAddTransaction.setBackground(new java.awt.Color(62, 158, 202));
        jButtonAddTransaction.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonAddTransaction.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddTransaction.setText("Add");
        jButtonAddTransaction.setBorder(null);
        jButtonAddTransaction.setContentAreaFilled(false);
        jButtonAddTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddTransaction.setOpaque(true);
        jButtonAddTransaction.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxDriver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTransaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txCustomerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txDestination, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddTransaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(534, 110));

        jButtonShowCars.setBackground(new java.awt.Color(62, 158, 202));
        jButtonShowCars.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonShowCars.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cars.png"))); // NOI18N
        jButtonShowCars.setText("Cars");
        jButtonShowCars.setBorder(null);
        jButtonShowCars.setContentAreaFilled(false);
        jButtonShowCars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonShowCars.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonShowCars.setIconTextGap(0);
        jButtonShowCars.setOpaque(true);
        jButtonShowCars.setPreferredSize(new java.awt.Dimension(120, 105));
        jButtonShowCars.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonShowCars.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonShowDrivers.setBackground(new java.awt.Color(62, 158, 202));
        jButtonShowDrivers.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonShowDrivers.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowDrivers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Drivers.png"))); // NOI18N
        jButtonShowDrivers.setText("Drivers");
        jButtonShowDrivers.setBorder(null);
        jButtonShowDrivers.setContentAreaFilled(false);
        jButtonShowDrivers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonShowDrivers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonShowDrivers.setIconTextGap(0);
        jButtonShowDrivers.setOpaque(true);
        jButtonShowDrivers.setPreferredSize(new java.awt.Dimension(120, 105));
        jButtonShowDrivers.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonShowDrivers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonShowCustomers.setBackground(new java.awt.Color(62, 158, 202));
        jButtonShowCustomers.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonShowCustomers.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Customers.png"))); // NOI18N
        jButtonShowCustomers.setText("Customers");
        jButtonShowCustomers.setBorder(null);
        jButtonShowCustomers.setContentAreaFilled(false);
        jButtonShowCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonShowCustomers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonShowCustomers.setIconTextGap(0);
        jButtonShowCustomers.setOpaque(true);
        jButtonShowCustomers.setPreferredSize(new java.awt.Dimension(120, 105));
        jButtonShowCustomers.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonShowCustomers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonShowTransactions.setBackground(new java.awt.Color(62, 158, 202));
        jButtonShowTransactions.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonShowTransactions.setForeground(new java.awt.Color(255, 255, 255));
        jButtonShowTransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Transactions.png"))); // NOI18N
        jButtonShowTransactions.setText("Transactions");
        jButtonShowTransactions.setBorder(null);
        jButtonShowTransactions.setContentAreaFilled(false);
        jButtonShowTransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonShowTransactions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonShowTransactions.setIconTextGap(0);
        jButtonShowTransactions.setOpaque(true);
        jButtonShowTransactions.setPreferredSize(new java.awt.Dimension(120, 105));
        jButtonShowTransactions.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonShowTransactions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonShowCars, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowDrivers, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonShowCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonShowCars, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonShowTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonShowCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonShowDrivers, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPaneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPaneMenu))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(574, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdNumberActionPerformed

    private void txDriverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDriverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDriverNameActionPerformed

    private void txBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBrandActionPerformed

    private void txCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCapacityActionPerformed

    private void txPoliceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPoliceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPoliceNumActionPerformed

    private void txCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCustomerNameActionPerformed

    private void txDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDestinationActionPerformed

    private void txDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDateActionPerformed

    private void txPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPriceActionPerformed

    private void jComboBoxCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCarActionPerformed

    private void jComboBoxDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDriverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCar;
    private javax.swing.JButton jButtonAddDriver;
    private javax.swing.JButton jButtonAddTransaction;
    private javax.swing.JButton jButtonShowCars;
    private javax.swing.JButton jButtonShowCustomers;
    private javax.swing.JButton jButtonShowDrivers;
    private javax.swing.JButton jButtonShowTransactions;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JComboBox<String> jComboBoxCar;
    private javax.swing.JComboBox<String> jComboBoxDriver;
    private javax.swing.JLabel jLabelAddCar;
    private javax.swing.JLabel jLabelAddDriver;
    private javax.swing.JLabel jLabelAdminName;
    private javax.swing.JLabel jLabelTransaction;
    private javax.swing.JPanel jPaneHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAddCar;
    private javax.swing.JPanel jPanelAddDriver;
    private javax.swing.JPanel jPanelAdminName;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    private javax.swing.JTextField txBrand;
    private javax.swing.JTextField txCapacity;
    private javax.swing.JTextField txCustomerName;
    private javax.swing.JTextField txDate;
    private javax.swing.JTextField txDestination;
    private javax.swing.JTextField txDriverName;
    private javax.swing.JTextField txIdNumber;
    private javax.swing.JTextField txPoliceNum;
    private javax.swing.JTextField txPrice;
    // End of variables declaration//GEN-END:variables

    
/// Button Action Listener    
    public void addActionListener(ActionListener e){
        jButtonAddCar.addActionListener(e);
        jButtonAddTransaction.addActionListener(e);
        jButtonAddDriver.addActionListener(e);
        jButtonShowCars.addActionListener(e);
        jButtonShowDrivers.addActionListener(e);
        jButtonShowCustomers.addActionListener(e);
        jButtonShowTransactions.addActionListener(e);
        jButtonSignOut.addActionListener(e);
    }

/// Admin Header       
    public JButton getjButtonSignOut() {
        return jButtonSignOut;
    }    
    public void setjLabelAdminName(String jLabelAdminName) {
        this.jLabelAdminName.setText(jLabelAdminName);
    }
 
/// Add Car  
    public JButton getjButtonAddCar() {
        return jButtonAddCar;
    }
    public String getTxBrand() {
        return txBrand.getText();
    }
    public String getTxCapacity() {
        return txCapacity.getText();
    }
    public String getTxPoliceNum() {
        return txPoliceNum.getText();
    }
    public void setjLabelAddCar(String jLabelAddCar) {
        this.jLabelAddCar.setText(jLabelAddCar);
    }
    

/// Add Driver   
    public JButton getjButtonAddDriver() {
        return jButtonAddDriver;
    }
    public String getTxDriverName() {
        return txDriverName.getText();
    }
    public String getTxIdNumber() {
        return txIdNumber.getText();
    }
    public String getjComboBoxCar() {
        int i = jComboBoxCar.getSelectedIndex();
        return jComboBoxCar.getItemAt(i);
    }
    public void setjComboBoxCar(List<String> jComboBoxCar) {
        this.jComboBoxCar.removeAllItems();
        this.jComboBoxCar.addItem("Cars");
        for(String o : jComboBoxCar){
            this.jComboBoxCar.addItem(o);
        }
    }
    public void setjLabelAddDriver(String jLabelAddDriver) {
        this.jLabelAddDriver.setText(jLabelAddDriver);
    }    

/// Add Transaction
    public JButton getjButtonAddTransaction() {
        return jButtonAddTransaction;
    }
    public String getjComboBoxDriver() {
        int i = jComboBoxDriver.getSelectedIndex();
        return jComboBoxDriver.getItemAt(i);
    }
    public void setjComboBoxDriver(List<String> jComboBoxDriver) {
        this.jComboBoxDriver.removeAllItems();
        this.jComboBoxDriver.addItem("Driver");
        for(String o : jComboBoxDriver){
            this.jComboBoxDriver.addItem(o);
        }
    }
    public String getTxCustomerName() {
        return txCustomerName.getText();
    }
    public String getTxDate() {
        return txDate.getText();
    }
    public String getTxDestination() {
        return txDestination.getText();
    }
    public String getTxPrice() {
        return txPrice.getText();
    }   
    
/// Show Database
    public JButton getjButtonShowCars() {
        return jButtonShowCars;
    }
    public JButton getjButtonShowCustomers() {
        return jButtonShowCustomers;
    }
    public JButton getjButtonShowDrivers() {
        return jButtonShowDrivers;
    }
    public JButton getjButtonShowTransactions() {
        return jButtonShowTransactions;
    }
    
    public void ResetView(){
        txBrand.setText("Brand");
        txCapacity.setText("Capacity");
        txCustomerName.setText("Name");
        txDate.setText("Date");
        txDestination.setText("Destination");
        txDriverName.setText("Name");
        txIdNumber.setText("Id Number");
        txPoliceNum.setText("Police Number");
        txPrice.setText("Price");
        jComboBoxCar.setSelectedIndex(0);
        jComboBoxDriver.setSelectedIndex(0);
    }
}
