/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author myusuf, fairuz, diniyal
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Adminpage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedAdmin = new javax.swing.JTabbedPane();
        jPanelSignUp = new javax.swing.JPanel();
        txSignUpName = new javax.swing.JTextField();
        jButtonSignUp = new javax.swing.JButton();
        jPasswordFieldSignUp = new javax.swing.JPasswordField();
        txSignUpIdNumber = new javax.swing.JTextField();
        txSignUpUsername = new javax.swing.JTextField();
        jLabelSignUp = new javax.swing.JLabel();
        jPanelSignIn = new javax.swing.JPanel();
        jButtonAdminSignIn = new javax.swing.JButton();
        txAdminSignInUsername = new javax.swing.JTextField();
        jPasswordFieldAdminSignIn = new javax.swing.JPasswordField();
        jPanelWelcome = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelWelcome1 = new javax.swing.JLabel();
        jLabelWelcome2 = new javax.swing.JLabel();
        jLabelSignIn = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel");
        setBackground(new java.awt.Color(252, 252, 252));
        setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(550, 500));
        setName("AdminPage"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(558, 480));

        jTabbedAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedAdmin.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jTabbedAdmin.setOpaque(true);

        jPanelSignUp.setBackground(new java.awt.Color(255, 255, 255));

        txSignUpName.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txSignUpName.setForeground(new java.awt.Color(204, 204, 204));
        txSignUpName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txSignUpName.setText("Name");
        txSignUpName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txSignUpName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txSignUpName.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txSignUpName.setPreferredSize(new java.awt.Dimension(122, 35));
        txSignUpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSignUpNameActionPerformed(evt);
            }
        });

        jButtonSignUp.setBackground(new java.awt.Color(62, 158, 202));
        jButtonSignUp.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignUp.setText("Sign Up");
        jButtonSignUp.setBorder(null);
        jButtonSignUp.setContentAreaFilled(false);
        jButtonSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSignUp.setOpaque(true);
        jButtonSignUp.setPreferredSize(new java.awt.Dimension(100, 35));
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });

        jPasswordFieldSignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldSignUp.setForeground(new java.awt.Color(62, 158, 202));
        jPasswordFieldSignUp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldSignUp.setText("password");
        jPasswordFieldSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));

        txSignUpIdNumber.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txSignUpIdNumber.setForeground(new java.awt.Color(204, 204, 204));
        txSignUpIdNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txSignUpIdNumber.setText("Id Number");
        txSignUpIdNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txSignUpIdNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txSignUpIdNumber.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txSignUpIdNumber.setPreferredSize(new java.awt.Dimension(122, 35));
        txSignUpIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSignUpIdNumberActionPerformed(evt);
            }
        });

        txSignUpUsername.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txSignUpUsername.setForeground(new java.awt.Color(204, 204, 204));
        txSignUpUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txSignUpUsername.setText("Username");
        txSignUpUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txSignUpUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txSignUpUsername.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txSignUpUsername.setPreferredSize(new java.awt.Dimension(122, 35));
        txSignUpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSignUpUsernameActionPerformed(evt);
            }
        });

        jLabelSignUp.setFont(new java.awt.Font("Typo Style Demo", 0, 14)); // NOI18N
        jLabelSignUp.setForeground(new java.awt.Color(153, 0, 0));
        jLabelSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelSignUpLayout = new javax.swing.GroupLayout(jPanelSignUp);
        jPanelSignUp.setLayout(jPanelSignUpLayout);
        jPanelSignUpLayout.setHorizontalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txSignUpName, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jButtonSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldSignUp)
                    .addComponent(txSignUpIdNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(txSignUpUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSignUpLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabelSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );
        jPanelSignUpLayout.setVerticalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignUpLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txSignUpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txSignUpIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSignUpLayout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jLabelSignUp)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        jTabbedAdmin.addTab("Sign Up", jPanelSignUp);

        jPanelSignIn.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAdminSignIn.setBackground(new java.awt.Color(62, 158, 202));
        jButtonAdminSignIn.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonAdminSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdminSignIn.setText("Sign In");
        jButtonAdminSignIn.setBorder(null);
        jButtonAdminSignIn.setContentAreaFilled(false);
        jButtonAdminSignIn.setOpaque(true);
        jButtonAdminSignIn.setPreferredSize(new java.awt.Dimension(100, 35));

        txAdminSignInUsername.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        txAdminSignInUsername.setForeground(new java.awt.Color(204, 204, 204));
        txAdminSignInUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txAdminSignInUsername.setText("Username");
        txAdminSignInUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));
        txAdminSignInUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txAdminSignInUsername.setDisabledTextColor(new java.awt.Color(210, 211, 213));
        txAdminSignInUsername.setPreferredSize(new java.awt.Dimension(122, 35));
        txAdminSignInUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAdminSignInUsernameActionPerformed(evt);
            }
        });

        jPasswordFieldAdminSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldAdminSignIn.setForeground(new java.awt.Color(62, 158, 202));
        jPasswordFieldAdminSignIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldAdminSignIn.setText("password");
        jPasswordFieldAdminSignIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 158, 202), 2));

        javax.swing.GroupLayout jPanelSignInLayout = new javax.swing.GroupLayout(jPanelSignIn);
        jPanelSignIn.setLayout(jPanelSignInLayout);
        jPanelSignInLayout.setHorizontalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdminSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldAdminSignIn)
                    .addComponent(txAdminSignInUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSignInLayout.setVerticalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txAdminSignInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldAdminSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jButtonAdminSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedAdmin.addTab("Sign In", jPanelSignIn);

        jPanelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelWelcome.setFont(new java.awt.Font("Typo Style Demo", 0, 45)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(62, 158, 202));
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelWelcome.setText("WELCOME");

        jLabelWelcome1.setFont(new java.awt.Font("Typo Style Demo", 0, 45)); // NOI18N
        jLabelWelcome1.setForeground(new java.awt.Color(62, 158, 202));
        jLabelWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelWelcome1.setText("TO TRAVEL");

        jLabelWelcome2.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelWelcome2.setForeground(new java.awt.Color(62, 158, 202));
        jLabelWelcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome2.setText("travel system information");

        jLabelSignIn.setFont(new java.awt.Font("Typo Style Demo", 0, 14)); // NOI18N
        jLabelSignIn.setForeground(new java.awt.Color(153, 0, 0));
        jLabelSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo.png"))); // NOI18N
        jLabelLogo.setToolTipText("");
        jLabelLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jLabelWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWelcome2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSignIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWelcome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWelcome2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedAdmin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txAdminSignInUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAdminSignInUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAdminSignInUsernameActionPerformed

    private void txSignUpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSignUpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSignUpUsernameActionPerformed

    private void txSignUpIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSignUpIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSignUpIdNumberActionPerformed

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void txSignUpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSignUpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSignUpNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdminSignIn;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSignIn;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JLabel jLabelWelcome1;
    private javax.swing.JLabel jLabelWelcome2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSignIn;
    private javax.swing.JPanel jPanelSignUp;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JPasswordField jPasswordFieldAdminSignIn;
    private javax.swing.JPasswordField jPasswordFieldSignUp;
    private javax.swing.JTabbedPane jTabbedAdmin;
    private javax.swing.JTextField txAdminSignInUsername;
    private javax.swing.JTextField txSignUpIdNumber;
    private javax.swing.JTextField txSignUpName;
    private javax.swing.JTextField txSignUpUsername;
    // End of variables declaration//GEN-END:variables


/// Admin Sign In
    public String getTxAdminSignInUsername() {
        return txAdminSignInUsername.getText();
    }
    public String getjPasswordFieldAdminSignIn() {
        return jPasswordFieldAdminSignIn.getText();
    }
    public JButton getjButtonAdminSignIn() {
        return jButtonAdminSignIn;
    }
    public void setjLabelSignIn(String jLabelSignIn) {
        this.jLabelSignIn.setText(jLabelSignIn);
    }
    
    
/// Admin Sign Up     
    public String getTxSignUpName() {
        return txSignUpName.getText();
    }
    public String getTxSignUpIdNumber() {
        return txSignUpIdNumber.getText();
    }
    public String getTxSignUpUsername() {
        return txSignUpUsername.getText();
    }
    public String getjPasswordFieldSignUp() {
        return jPasswordFieldSignUp.getText();
    }
    public JButton getjButtonSignUp() {
        return jButtonSignUp;
    }
    public void setjLabelSignUp(String jLabelSignUp) {
        this.jLabelSignUp.setText(jLabelSignUp);
    }
    
    
/// Button Action Listener    
    public void addActionListener(ActionListener e){
        jButtonSignUp.addActionListener(e);
        jButtonAdminSignIn.addActionListener(e);
    }
    
/// Reset All Text Field
    public void ResetView(){
        txAdminSignInUsername.setText("Username");
        jPasswordFieldAdminSignIn.setText("Password");
        
        txSignUpName.setText("Name");
        txSignUpIdNumber.setText("Id Number");
        txSignUpUsername.setText("Username");
        jPasswordFieldSignUp.setText("Password");
    }          
    
}
