/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author myusuf, fairuz, diniyal
 */
public class ViewCarsPage extends javax.swing.JFrame {

    /**
     * Creates new form Adminpage
     */
    public ViewCarsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPaneHeader = new javax.swing.JPanel();
        jButtonSignOut = new javax.swing.JButton();
        jPanelAdminName = new javax.swing.JPanel();
        jLabelAdminName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelViewCars = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCars = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetails = new javax.swing.JTextArea();
        jLabelListCars = new javax.swing.JLabel();
        jLabelList = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel");
        setBackground(new java.awt.Color(252, 252, 252));
        setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(550, 500));
        setName("AdminPage"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(558, 480));

        jPaneHeader.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSignOut.setBackground(new java.awt.Color(62, 158, 202));
        jButtonSignOut.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonSignOut.setForeground(new java.awt.Color(62, 158, 202));
        jButtonSignOut.setText("SignOut");
        jButtonSignOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 211, 213)));
        jButtonSignOut.setContentAreaFilled(false);
        jButtonSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSignOut.setMultiClickThreshhold(5L);
        jButtonSignOut.setPreferredSize(new java.awt.Dimension(100, 35));

        jPanelAdminName.setBackground(new java.awt.Color(62, 158, 202));

        jLabelAdminName.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelAdminName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdminName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAdminName.setPreferredSize(new java.awt.Dimension(200, 35));

        javax.swing.GroupLayout jPanelAdminNameLayout = new javax.swing.GroupLayout(jPanelAdminName);
        jPanelAdminName.setLayout(jPanelAdminNameLayout);
        jPanelAdminNameLayout.setHorizontalGroup(
            jPanelAdminNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminNameLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabelAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAdminNameLayout.setVerticalGroup(
            jPanelAdminNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAdminName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPaneHeaderLayout = new javax.swing.GroupLayout(jPaneHeader);
        jPaneHeader.setLayout(jPaneHeaderLayout);
        jPaneHeaderLayout.setHorizontalGroup(
            jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAdminName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneHeaderLayout.setVerticalGroup(
            jPaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelViewCars.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelViewCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelViewCars.setText("View Cars");

        jListCars.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jListCars.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListCars);

        jScrollPane2.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N

        jTextAreaDetails.setColumns(20);
        jTextAreaDetails.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jTextAreaDetails.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetails);

        jLabelListCars.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelListCars.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelListCars.setText("Details :");

        jLabelList.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jLabelList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelList.setText("List of Cars");

        jButtonEdit.setBackground(new java.awt.Color(62, 158, 202));
        jButtonEdit.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("Edit");
        jButtonEdit.setBorder(null);
        jButtonEdit.setContentAreaFilled(false);
        jButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdit.setIconTextGap(0);
        jButtonEdit.setOpaque(true);
        jButtonEdit.setPreferredSize(new java.awt.Dimension(120, 105));

        jButtonDelete.setBackground(new java.awt.Color(62, 158, 202));
        jButtonDelete.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(null);
        jButtonDelete.setContentAreaFilled(false);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.setIconTextGap(0);
        jButtonDelete.setOpaque(true);
        jButtonDelete.setPreferredSize(new java.awt.Dimension(120, 105));

        jButtonHome.setBackground(new java.awt.Color(62, 158, 202));
        jButtonHome.setFont(new java.awt.Font("Typo Style Demo", 0, 18)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("Home");
        jButtonHome.setBorder(null);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHome.setIconTextGap(0);
        jButtonHome.setOpaque(true);
        jButtonHome.setPreferredSize(new java.awt.Dimension(120, 105));

        jLabelStatus.setFont(new java.awt.Font("Typo Style Demo", 0, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(153, 0, 0));
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelViewCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabelListCars, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelViewCars, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelListCars, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPaneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JLabel jLabelAdminName;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JLabel jLabelListCars;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelViewCars;
    private javax.swing.JList<String> jListCars;
    private javax.swing.JPanel jPaneHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAdminName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDetails;
    // End of variables declaration//GEN-END:variables

    
/// Button Action Listener    
    public void addActionListener(ActionListener e){
        jButtonHome.addActionListener(e);
        jButtonSignOut.addActionListener(e);
        jButtonEdit.addActionListener(e);
        jButtonDelete.addActionListener(e);
    }
   
    public void addMouseAdapter(MouseAdapter e){
        jListCars.addMouseListener(e);
    }
/// Admin Header       
    public JButton getjButtonSignOut() {
        return jButtonSignOut;
    }    
    public void setjLabelAdminName(String jLabelAdminName) {
        this.jLabelAdminName.setText(jLabelAdminName);
    }
    
/// Show Cars
    public int getSelectedtCar() {
        return jListCars.getSelectedIndex();
    }
    public void setjListCars(String[] jListCars) {
        this.jListCars.setListData(jListCars);
    }
    public void setjTextAreaDetails(String jTextAreaDetails) {
        this.jTextAreaDetails.setText(jTextAreaDetails);
    }
    public JList getjListCars() {
        return jListCars;
    }

    public void setjLabelStatus(String jLabelStatus) {
        this.jLabelStatus.setText(jLabelStatus);
;    }

    
    
/// Delete Car
    public JButton getjButtonDelete() {
        return jButtonDelete;
    }
    
/// Edit Car
    public JButton getjButtonEdit() {
        return jButtonEdit;
    }    
    
/// Show Database
    public JButton getjButtonHome() {
        return jButtonHome;
    }
    
    public void ResetView(){
           jListCars.clearSelection();
           jTextAreaDetails.setText("");
    }
}
